import { NextRequest, NextResponse } from "next/server";
import type { Slide, ThemeName, StyleName } from "@/types/slide";
import { THEMES, VISUAL_STYLES } from "@/lib/presentation/themes";

// Dynamic import for pptxgenjs (ESM module)
async function createPptx(slides: Slide[], title: string, themeName: ThemeName, styleName: StyleName) {
  const PptxGenJS = (await import("pptxgenjs")).default;
  const theme = THEMES[themeName] || THEMES.blue;
  const style = VISUAL_STYLES[styleName] || VISUAL_STYLES.modern;
  const pptx = new PptxGenJS();

  pptx.author = "SlideForge";
  pptx.title = title || "Presentation";
  pptx.subject = "Generated by SlideForge";
  pptx.layout = "LAYOUT_WIDE";

  const pc = theme.primary.replace("#", "");
  const sc = theme.secondary.replace("#", "");
  const bg = theme.slideBg.replace("#", "");
  const bgAlt = theme.slideBgAlt.replace("#", "");
  const tc = theme.text.replace("#", "");
  const mc = theme.textMuted.replace("#", "");
  const ac = theme.accent.replace("#", "");

  slides.forEach((slide, index) => {
    const pptSlide = pptx.addSlide();
    pptSlide.background = { color: index % 2 === 0 ? bg : bgAlt };

    const headingSize = parseInt(style.headingSize) + 2;

    switch (slide.layout) {
      case "title": {
        pptSlide.addText(slide.title, {
          x: 0.8, y: 2.2, w: 11.8, h: 1.5,
          fontSize: parseInt(style.titleSize) + 4,
          fontFace: "Arial", color: pc, bold: true, align: "center", wrap: true,
        });
        if (slide.subtitle) {
          pptSlide.addText(slide.subtitle, {
            x: 2.0, y: 3.8, w: 9.3, h: 0.8,
            fontSize: 18, fontFace: "Arial", color: mc, align: "center", wrap: true,
          });
        }
        pptSlide.addShape("rect", { x: 5.2, y: 3.55, w: 3.0, h: 0.06, fill: { color: pc } });
        break;
      }
      case "section": {
        pptSlide.addShape("rect", { x: 0.8, y: 2.8, w: 1.0, h: 0.08, fill: { color: pc } });
        pptSlide.addText(slide.title, {
          x: 0.8, y: 3.1, w: 11.8, h: 1.2,
          fontSize: parseInt(style.titleSize) + 2,
          fontFace: "Arial", color: tc, bold: true, wrap: true,
        });
        if (slide.subtitle) {
          pptSlide.addText(slide.subtitle, {
            x: 0.8, y: 4.4, w: 11.8, h: 0.7,
            fontSize: 16, fontFace: "Arial", color: mc, wrap: true,
          });
        }
        break;
      }
      case "bullets": {
        pptSlide.addText(slide.title, {
          x: 0.8, y: 0.5, w: 11.8, h: 0.8,
          fontSize: headingSize, fontFace: "Arial", color: tc, bold: true, wrap: true,
        });
        const bullets = (slide.bullets || []).map((b) => ({
          text: b,
          options: { fontSize: parseInt(style.bodySize), color: tc, bullet: { code: "2022" }, paraSpaceAfter: 10 },
        }));
        pptSlide.addText(bullets, { x: 1.0, y: 1.6, w: 11.0, h: 4.8, fontFace: "Arial", valign: "middle", wrap: true });
        break;
      }
      case "two_column": {
        pptSlide.addText(slide.title, {
          x: 0.8, y: 0.5, w: 11.8, h: 0.8,
          fontSize: headingSize, fontFace: "Arial", color: tc, bold: true, wrap: true,
        });
        const bullets = (slide.left?.bullets || []).map((b) => ({
          text: b,
          options: { fontSize: parseInt(style.bodySize), color: tc, bullet: { code: "2022" }, paraSpaceAfter: 10 },
        }));
        pptSlide.addText(bullets, { x: 0.8, y: 1.6, w: 5.5, h: 4.8, fontFace: "Arial", valign: "middle", wrap: true });
        pptSlide.addShape("roundRect", {
          x: 7.0, y: 2.0, w: 5.2, h: 3.5,
          fill: { color: "1e293b" }, line: { color: pc, width: 1 }, rectRadius: 0.15,
        });
        pptSlide.addText(slide.right?.visual || "📊", {
          x: 7.0, y: 2.5, w: 5.2, h: 2.0, fontSize: 48, align: "center", valign: "middle",
        });
        if (slide.right?.label) {
          pptSlide.addText(slide.right.label, {
            x: 7.0, y: 4.2, w: 5.2, h: 0.8,
            fontSize: 13, fontFace: "Arial", color: mc, align: "center", wrap: true,
          });
        }
        break;
      }
      case "stats": {
        pptSlide.addText(slide.title, {
          x: 0.8, y: 0.5, w: 11.8, h: 0.8,
          fontSize: headingSize, fontFace: "Arial", color: tc, bold: true, wrap: true,
        });
        const stats = slide.stats || [];
        const cardW = 3.4;
        const gap = 0.4;
        const totalW = stats.length * cardW + (stats.length - 1) * gap;
        const startX = (13.33 - totalW) / 2;
        stats.forEach((s, i) => {
          const x = startX + i * (cardW + gap);
          pptSlide.addShape("roundRect", { x, y: 2.0, w: cardW, h: 3.2, fill: { color: "1e293b" }, line: { color: pc, width: 1 }, rectRadius: 0.15 });
          pptSlide.addText(s.number, { x, y: 2.5, w: cardW, h: 1.5, fontSize: 36, fontFace: "Arial", color: pc, bold: true, align: "center", valign: "middle" });
          pptSlide.addText(s.label, { x: x + 0.3, y: 4.0, w: cardW - 0.6, h: 0.8, fontSize: 13, fontFace: "Arial", color: mc, align: "center", wrap: true });
        });
        break;
      }
      case "key_points": {
        pptSlide.addText(slide.title, {
          x: 0.8, y: 0.5, w: 11.8, h: 0.8,
          fontSize: headingSize, fontFace: "Arial", color: tc, bold: true, wrap: true,
        });
        const points = slide.points || [];
        const cw = 5.5, ch = 2.0, gx = 0.6, gy = 0.4;
        points.forEach((p, i) => {
          const col = i % 2, row = Math.floor(i / 2);
          const x = 0.8 + col * (cw + gx), y = 1.6 + row * (ch + gy);
          pptSlide.addShape("roundRect", { x, y, w: cw, h: ch, fill: { color: "1e293b" }, line: { color: pc, width: 1 }, rectRadius: 0.12 });
          pptSlide.addText(p.title, { x: x + 0.3, y: y + 0.3, w: cw - 0.6, h: 0.5, fontSize: 15, fontFace: "Arial", color: ac, bold: true, wrap: true });
          pptSlide.addText(p.description, { x: x + 0.3, y: y + 0.9, w: cw - 0.6, h: 0.8, fontSize: 12, fontFace: "Arial", color: mc, wrap: true });
        });
        break;
      }
      case "flow": {
        pptSlide.addText(slide.title, {
          x: 0.8, y: 0.5, w: 11.8, h: 0.8,
          fontSize: headingSize, fontFace: "Arial", color: tc, bold: true, wrap: true,
        });
        const steps = slide.steps || [];
        const bw = 2.2, aw = 0.5;
        const tw = steps.length * bw + (steps.length - 1) * aw;
        const sx = (13.33 - tw) / 2;
        steps.forEach((s, i) => {
          const x = sx + i * (bw + aw);
          pptSlide.addShape("roundRect", { x, y: 2.5, w: bw, h: 2.5, fill: { color: "1e293b" }, line: { color: pc, width: 1 }, rectRadius: 0.12 });
          pptSlide.addText(String(i + 1), { x, y: 2.7, w: bw, h: 0.8, fontSize: 24, fontFace: "Arial", color: pc, bold: true, align: "center" });
          pptSlide.addText(s, { x: x + 0.2, y: 3.5, w: bw - 0.4, h: 1.2, fontSize: 12, fontFace: "Arial", color: tc, align: "center", valign: "middle", wrap: true });
          if (i < steps.length - 1) {
            pptSlide.addText("→", { x: x + bw, y: 3.2, w: aw, h: 1.0, fontSize: 24, color: mc, align: "center", valign: "middle" });
          }
        });
        break;
      }
      case "quote": {
        pptSlide.addText('"', { x: 1.5, y: 1.5, w: 2.0, h: 1.5, fontSize: 72, color: pc, fontFace: "Georgia", bold: true, align: "left" });
        pptSlide.addText(slide.quote || "", {
          x: 1.5, y: 2.8, w: 10.0, h: 2.0,
          fontSize: 20, fontFace: "Arial", color: tc, italic: true, align: "center", valign: "middle", wrap: true,
        });
        if (slide.attribution) {
          pptSlide.addText(`— ${slide.attribution}`, { x: 2.0, y: 5.0, w: 9.0, h: 0.6, fontSize: 13, fontFace: "Arial", color: mc, align: "center" });
        }
        break;
      }
      default: {
        pptSlide.addText(slide.title, {
          x: 0.8, y: 0.5, w: 11.8, h: 0.8,
          fontSize: headingSize, fontFace: "Arial", color: tc, bold: true, wrap: true,
        });
        const bullets = (slide.bullets || []).map((b) => ({
          text: b,
          options: { fontSize: parseInt(style.bodySize), color: tc, bullet: { code: "2022" }, paraSpaceAfter: 10 },
        }));
        pptSlide.addText(bullets, { x: 1.0, y: 1.6, w: 11.0, h: 4.8, fontFace: "Arial", valign: "middle", wrap: true });
      }
    }

    if (slide.speaker_notes) {
      pptSlide.addNotes(slide.speaker_notes);
    }

    pptSlide.addText(`${index + 1} / ${slides.length}`, {
      x: 9.0, y: 6.8, w: 1.2, h: 0.3, fontSize: 9, color: mc, align: "right",
    });
  });

  return pptx;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { slides, title, themeName, styleName } = body as {
      slides: Slide[];
      title: string;
      themeName: ThemeName;
      styleName: StyleName;
    };

    if (!slides || !Array.isArray(slides) || slides.length === 0) {
      return NextResponse.json({ error: "Slides data is required" }, { status: 400 });
    }

    const pptx = await createPptx(slides, title, themeName, styleName);
    const arrayBuf: ArrayBuffer = await pptx.write({ outputType: "arraybuffer" }) as unknown as ArrayBuffer;

    const safeTitle = (title || "presentation").replace(/[^a-zA-Z0-9 ]/g, "").trim().replace(/\s+/g, "_");

    return new NextResponse(arrayBuf, {
      status: 200,
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "Content-Disposition": `attachment; filename="${safeTitle || "presentation"}.pptx"`,
      },
    });
  } catch (error) {
    console.error("PPTX export error:", error);
    const message = error instanceof Error ? error.message : "Export failed";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}