"use client";

import { useEffect, useState, useCallback } from "react";
import { usePresentationStore } from "@/store/presentation-store";
import { THEMES, VISUAL_STYLES, gradientCSS, slideBackground } from "@/lib/presentation/themes";
import type { Slide, ThemeName, StyleName } from "@/types/slide";
import type { AiProviderSetting } from "@/types/ai-provider";
import {
  Zap, Settings, ChevronLeft, ChevronRight, Copy, Download, FileText,
  X, Eye, EyeOff, Monitor, Loader2
} from "lucide-react";

export default function Home() {
  const store = usePresentationStore();
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [apiKeyInput, setApiKeyInput] = useState("");
  const [showKey, setShowKey] = useState(false);
  const [inputTitle, setInputTitle] = useState("");
  const [inputText, setInputText] = useState("");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    store.loadFromStorage();
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const getActiveProviderSetting = useCallback((): AiProviderSetting | null => {
    const p = store.providers.find(pr => pr.name === store.activeProviderName);
    return p || store.providers[0] || null;
  }, [store.providers, store.activeProviderName]);

  const handleGenerate = useCallback(async () => {
    if (!inputText.trim()) return;
    const provider = getActiveProviderSetting();
    if (!provider) {
      store.setError("No AI provider configured. Open Settings to add one.");
      return;
    }
    if (provider.providerType !== "ollama" && !provider.apiKey && !apiKeyInput) {
      setSettingsOpen(true);
      store.setError("This provider requires an API key. Add it in Settings.");
      return;
    }
    const providerWithKey = { ...provider, apiKey: provider.apiKey || apiKeyInput };

    store.setGenerating(true);
    store.setProgress(10, "Analyzing content...");
    try {
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: inputTitle,
          text: inputText,
          slideCount: store.slideCount,
          style: store.styleName,
          audience: store.audience,
          provider: providerWithKey,
        }),
      });
      store.setProgress(60, "Building slides...");
      if (!res.ok) {
        const err = await res.json().catch(() => ({ error: "Generation failed" }));
        throw new Error(err.error || `HTTP ${res.status}`);
      }
      const data = await res.json();
      store.setProgress(90, "Finalizing...");
      store.setTitle(data.title || inputTitle);
      store.setSlides(data.slides || []);
      if (data.executiveSummary) store.setExecutiveSummary(data.executiveSummary);
      if (data.keyTakeaways) store.setKeyTakeaways(data.keyTakeaways);
      await new Promise(r => setTimeout(r, 300));
      store.setProgress(100, "Done!");
    } catch (err) {
      store.setError(err instanceof Error ? err.message : "Generation failed");
    } finally {
      store.setGenerating(false);
    }
  }, [inputText, inputTitle, store, getActiveProviderSetting, apiKeyInput]);

  const handleExportPptx = useCallback(async () => {
    try {
      const res = await fetch("/api/export/pptx", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          slides: store.slides,
          title: store.title,
          themeName: store.themeName,
          styleName: store.styleName,
        }),
      });
      if (!res.ok) throw new Error("Export failed");
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${(store.title || "presentation").replace(/[^a-zA-Z0-9 ]/g, "").trim().replace(/\s+/g, "_")}.pptx`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      store.setError(err instanceof Error ? err.message : "Export failed");
    }
  }, [store]);

  const handleExportScript = useCallback(() => {
    let text = `PRESENTER SCRIPT\n${"=".repeat(50)}\n`;
    text += `Presentation: ${store.title || "Untitled"}\n`;
    text += `Generated by SlideForge\n${"=".repeat(50)}\n\n`;
    store.slides.forEach((slide, i) => {
      text += `--- SLIDE ${i + 1}: ${slide.title || slide.type} ---\n\n`;
      text += (slide.speaker_notes || "(No script)") + "\n\n";
    });
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${(store.title || "script").replace(/[^a-zA-Z0-9 ]/g, "").trim().replace(/\s+/g, "_")}_script.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }, [store]);

  const handleCopyScript = useCallback(() => {
    let text = "";
    store.slides.forEach((slide, i) => {
      if (slide.speaker_notes) text += `Slide ${i + 1} (${slide.title}):\n${slide.speaker_notes}\n\n`;
    });
    navigator.clipboard.writeText(text);
  }, [store.slides]);

  const handleSaveSettings = useCallback(() => {
    if (apiKeyInput) {
      const updated = store.providers.map(p =>
        p.name === store.activeProviderName ? { ...p, apiKey: apiKeyInput } : p
      );
      store.setProviders(updated);
    }
    setSettingsOpen(false);
  }, [apiKeyInput, store]);

  if (!mounted) return null;

  const theme = THEMES[store.themeName];
  const style = VISUAL_STYLES[store.styleName];
  const currentSlide = store.slides[store.currentSlideIndex];

  return (
    <div className="h-screen flex flex-col overflow-hidden">
      {/* Header */}
      <header className="flex items-center justify-between px-5 h-[52px] bg-[#1a1d27] border-b border-[#2e3348] shrink-0">
        <div className="flex items-center gap-3">
          <Monitor className="w-6 h-6 text-blue-500" />
          <span className="font-bold text-lg tracking-tight">SlideForge</span>
        </div>
        <div className="flex items-center gap-2">
          {store.error && (
            <span className="text-red-400 text-xs max-w-[300px] truncate">{store.error}</span>
          )}
          <button
            onClick={() => setSettingsOpen(true)}
            className="p-2 rounded-md hover:bg-[#2a2e3d] text-gray-400 hover:text-gray-200 transition"
          >
            <Settings className="w-5 h-5" />
          </button>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 grid grid-cols-[300px_1fr_320px] overflow-hidden">
        {/* Left Panel - Input */}
        <aside className="bg-[#1a1d27] border-r border-[#2e3348] flex flex-col overflow-hidden">
          <div className="px-4 py-3 border-b border-[#2e3348]">
            <h2 className="text-xs font-semibold uppercase tracking-widest text-gray-400">Input</h2>
          </div>
          <div className="flex-1 overflow-y-auto p-4 space-y-4">
            <div>
              <label className="block text-xs font-medium text-gray-400 mb-1.5">Presentation Title</label>
              <input
                type="text" value={inputTitle} onChange={e => setInputTitle(e.target.value)}
                placeholder="e.g., Introduction to Machine Learning"
                className="w-full px-3 py-2 bg-[#242836] border border-[#2e3348] rounded-md text-sm text-gray-100 focus:border-blue-500 focus:ring-1 focus:ring-blue-500/30 outline-none transition"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-400 mb-1.5">
                Your Content <span className="text-gray-600 font-normal">(paste text, notes, or topic)</span>
              </label>
              <textarea
                value={inputText} onChange={e => setInputText(e.target.value)}
                rows={10}
                placeholder="Paste your text content here. The AI will analyze it and create a structured presentation with slides, visuals, and a presenter script..."
                className="w-full px-3 py-2 bg-[#242836] border border-[#2e3348] rounded-md text-sm text-gray-100 focus:border-blue-500 focus:ring-1 focus:ring-blue-500/30 outline-none transition resize-y min-h-[100px]"
              />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-medium text-gray-400 mb-1.5">Slide Count</label>
                <select
                  value={store.slideCount} onChange={e => store.setSlideCount(e.target.value)}
                  className="w-full px-3 py-2 bg-[#242836] border border-[#2e3348] rounded-md text-sm text-gray-100 outline-none"
                >
                  <option value="auto">Auto</option>
                  <option value="5">5 slides</option>
                  <option value="8">8 slides</option>
                  <option value="10">10 slides</option>
                  <option value="15">15 slides</option>
                  <option value="20">20 slides</option>
                </select>
              </div>
              <div>
                <label className="block text-xs font-medium text-gray-400 mb-1.5">Visual Style</label>
                <select
                  value={store.styleName} onChange={e => store.setStyleName(e.target.value as StyleName)}
                  className="w-full px-3 py-2 bg-[#242836] border border-[#2e3348] rounded-md text-sm text-gray-100 outline-none"
                >
                  <option value="modern">Modern</option>
                  <option value="minimal">Minimal</option>
                  <option value="bold">Bold</option>
                  <option value="corporate">Corporate</option>
                  <option value="creative">Creative</option>
                </select>
              </div>
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-400 mb-1.5">Target Audience <span className="text-gray-600">(optional)</span></label>
              <input
                type="text" value={store.audience} onChange={e => store.setAudience(e.target.value)}
                placeholder="e.g., High school students"
                className="w-full px-3 py-2 bg-[#242836] border border-[#2e3348] rounded-md text-sm text-gray-100 focus:border-blue-500 focus:ring-1 focus:ring-blue-500/30 outline-none transition"
              />
            </div>
            <button
              onClick={handleGenerate}
              disabled={store.isGenerating || !inputText.trim()}
              className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-gradient-to-r from-blue-600 to-violet-600 text-white font-semibold rounded-lg hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed transition shadow-lg shadow-blue-500/20"
            >
              {store.isGenerating ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <Zap className="w-4 h-4" />
              )}
              {store.isGenerating ? "Generating..." : "Generate Presentation"}
            </button>
            {store.isGenerating && (
              <div className="space-y-1">
                <div className="h-1 bg-[#242836] rounded-full overflow-hidden">
                  <div
                    className="h-full bg-gradient-to-r from-blue-500 to-violet-500 rounded-full transition-all duration-500"
                    style={{ width: `${store.progress}%` }}
                  />
                </div>
                <p className="text-xs text-gray-500 text-center">{store.progressMessage}</p>
              </div>
            )}
          </div>
        </aside>

        {/* Center Panel - Slide Preview */}
        <section className="bg-[#0f1117] flex flex-col overflow-hidden border-x border-[#2e3348]">
          <div className="px-4 py-3 border-b border-[#2e3348] flex items-center justify-between bg-[#1a1d27]">
            <h2 className="text-xs font-semibold uppercase tracking-widest text-gray-400">Slides Preview</h2>
            <div className="flex items-center gap-2">
              <button onClick={() => store.navigateSlide(-1)} disabled={store.currentSlideIndex <= 0} className="p-1 rounded hover:bg-[#2a2e3d] text-gray-400 disabled:opacity-30 disabled:cursor-not-allowed">
                <ChevronLeft className="w-4 h-4" />
              </button>
              <span className="text-xs text-gray-500 tabular-nums min-w-[40px] text-center">
                {store.slides.length > 0 ? `${store.currentSlideIndex + 1} / ${store.slides.length}` : "0 / 0"}
              </span>
              <button onClick={() => store.navigateSlide(1)} disabled={store.currentSlideIndex >= store.slides.length - 1} className="p-1 rounded hover:bg-[#2a2e3d] text-gray-400 disabled:opacity-30 disabled:cursor-not-allowed">
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </div>
          <div className="flex-1 flex items-center justify-center p-6 overflow-hidden">
            {store.slides.length === 0 ? (
              <div className="text-center text-gray-600">
                <Monitor className="w-16 h-16 mx-auto mb-4 opacity-30" />
                <h3 className="text-lg font-semibold text-gray-400 mb-2">No slides yet</h3>
                <p className="text-sm max-w-[280px]">Enter your content and click "Generate Presentation" to create slides</p>
              </div>
            ) : currentSlide ? (
              <div className="w-full max-w-[720px] aspect-video rounded-xl overflow-hidden shadow-2xl shadow-black/50">
                <SlidePreview slide={currentSlide} index={store.currentSlideIndex} total={store.slides.length} themeName={store.themeName} styleName={store.styleName} />
              </div>
            ) : null}
          </div>
          {/* Export Bar */}
          {store.slides.length > 0 && (
            <div className="flex items-center justify-center gap-3 px-4 py-3 border-t border-[#2e3348] bg-[#1a1d27]">
              <button onClick={handleExportPptx} className="flex items-center gap-2 px-4 py-2 bg-[#242836] border border-[#2e3348] rounded-lg text-sm font-medium hover:bg-[#2a2e3d] transition">
                <Download className="w-4 h-4" /> Download PPTX
              </button>
              <button onClick={handleExportScript} className="flex items-center gap-2 px-4 py-2 bg-[#242836] border border-[#2e3348] rounded-lg text-sm font-medium hover:bg-[#2a2e3d] transition">
                <FileText className="w-4 h-4" /> Download Script
              </button>
            </div>
          )}
        </section>

        {/* Right Panel - Script */}
        <aside className="bg-[#1a1d27] border-l border-[#2e3348] flex flex-col overflow-hidden">
          <div className="px-4 py-3 border-b border-[#2e3348] flex items-center justify-between">
            <h2 className="text-xs font-semibold uppercase tracking-widest text-gray-400">Presenter Script</h2>
            {store.slides.length > 0 && (
              <button onClick={handleCopyScript} className="p-1 rounded hover:bg-[#2a2e3d] text-gray-400" title="Copy script">
                <Copy className="w-4 h-4" />
              </button>
            )}
          </div>
          <div className="flex-1 overflow-y-auto p-4">
            {store.slides.length === 0 ? (
              <div className="text-center text-gray-600 py-12">
                <FileText className="w-12 h-12 mx-auto mb-3 opacity-30" />
                <h3 className="text-sm font-semibold text-gray-400 mb-1">No script yet</h3>
                <p className="text-xs">Generate a presentation to see the presenter script</p>
              </div>
            ) : (
              <div className="space-y-4">
                {store.executiveSummary && (
                  <div className="p-3 bg-[#242836] rounded-lg border border-[#2e3348]">
                    <h4 className="text-xs font-semibold text-blue-400 mb-1">Executive Summary</h4>
                    <p className="text-xs text-gray-400 leading-relaxed">{store.executiveSummary}</p>
                  </div>
                )}
                {store.slides.map((slide, i) => {
                  if (!slide.speaker_notes && (slide.type === "title" || slide.type === "ending")) return null;
                  if (!slide.speaker_notes) return null;
                  return (
                    <div key={i} className="p-3 bg-[#242836] rounded-lg border-l-[3px] border-blue-500">
                      <div className="flex items-center gap-2 mb-2 pb-2 border-b border-[#2e3348]">
                        <span className="text-[10px] font-bold text-blue-400 bg-blue-500/10 px-2 py-0.5 rounded-full">Slide {i + 1}</span>
                        <span className="text-xs font-semibold text-gray-200 truncate">{slide.title}</span>
                      </div>
                      <p className="text-xs text-gray-400 leading-relaxed">{slide.speaker_notes}</p>
                      {slide.transition && (
                        <p className="text-[10px] text-gray-600 mt-2 italic">→ {slide.transition}</p>
                      )}
                    </div>
                  );
                })}
                {store.keyTakeaways.length > 0 && (
                  <div className="p-3 bg-[#242836] rounded-lg border border-[#2e3348]">
                    <h4 className="text-xs font-semibold text-amber-400 mb-2">Key Takeaways</h4>
                    <ul className="space-y-1">
                      {store.keyTakeaways.map((t, i) => (
                        <li key={i} className="text-xs text-gray-400 flex items-start gap-2">
                          <span className="text-amber-500 mt-0.5">•</span> {t}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            )}
          </div>
        </aside>
      </main>

      {/* Settings Modal */}
      {settingsOpen && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50" onClick={e => { if (e.target === e.currentTarget) setSettingsOpen(false); }}>
          <div className="bg-[#1a1d27] border border-[#2e3348] rounded-xl w-[440px] max-w-[90vw] shadow-2xl">
            <div className="flex items-center justify-between px-5 py-4 border-b border-[#2e3348]">
              <h3 className="font-semibold">Settings</h3>
              <button onClick={() => setSettingsOpen(false)} className="p-1 rounded hover:bg-[#2a2e3d] text-gray-400"><X className="w-4 h-4" /></button>
            </div>
            <div className="p-5 space-y-4">
              <div>
                <label className="block text-xs font-medium text-gray-400 mb-1.5">AI Provider</label>
                <select
                  value={store.activeProviderName}
                  onChange={e => store.setActiveProvider(e.target.value)}
                  className="w-full px-3 py-2 bg-[#242836] border border-[#2e3348] rounded-md text-sm text-gray-100 outline-none"
                >
                  {store.providers.map(p => (
                    <option key={p.name} value={p.name}>{p.name} — {p.modelId}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-xs font-medium text-gray-400 mb-1.5">API Key <span className="text-gray-600 font-normal">(if required)</span></label>
                <div className="flex gap-2">
                  <input
                    type={showKey ? "text" : "password"}
                    value={apiKeyInput} onChange={e => setApiKeyInput(e.target.value)}
                    placeholder="Enter API key"
                    className="flex-1 px-3 py-2 bg-[#242836] border border-[#2e3348] rounded-md text-sm text-gray-100 outline-none"
                  />
                  <button onClick={() => setShowKey(!showKey)} className="p-2 rounded-md bg-[#242836] border border-[#2e3348] text-gray-400 hover:text-gray-200">
                    {showKey ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                  </button>
                </div>
                <p className="text-[11px] text-gray-600 mt-1">Ollama (local) doesn't need a key. For Groq/Together/etc., get a free key from their website.</p>
              </div>
              <div>
                <label className="block text-xs font-medium text-gray-400 mb-1.5">Theme Colors</label>
                <div className="flex gap-2.5">
                  {(Object.keys(THEMES) as ThemeName[]).map(name => (
                    <button
                      key={name}
                      onClick={() => store.setThemeName(name)}
                      className={`w-9 h-9 rounded-md border-2 transition hover:scale-110 ${store.themeName === name ? "border-white shadow-lg" : "border-transparent"}`}
                      style={{ background: gradientCSS(THEMES[name]) }}
                      title={name}
                    />
                  ))}
                </div>
              </div>
              <button onClick={handleSaveSettings} className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-gradient-to-r from-blue-600 to-violet-600 text-white font-semibold rounded-lg hover:opacity-90 transition">
                Save Settings
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

/* ===== Slide Preview Component (Enhanced) ===== */
function SlidePreview({ slide, index, total, themeName, styleName }: { slide: Slide; index: number; total: number; themeName: ThemeName; styleName: StyleName }) {
  const theme = THEMES[themeName];
  const style = VISUAL_STYLES[styleName];
  const bg = slideBackground(theme, styleName, index);
  const bgStyle = bg.includes("linear-gradient") ? { background: bg } : { background: bg };
  const gradient = gradientCSS(theme);

  const decor = style.useDecorations ? (
    <>
      <div className="decorative-circle" style={{ width: 350, height: 350, top: -120, right: -100, background: theme.primary }} />
      <div className="decorative-circle" style={{ width: 250, height: 250, bottom: -80, left: -60, background: theme.secondary }} />
      {/* Subtle grid lines */}
      <div style={{
        position: "absolute", inset: 0, opacity: 0.02, pointerEvents: "none",
        backgroundImage: `linear-gradient(${theme.primary}33 1px, transparent 1px), linear-gradient(90deg, ${theme.primary}33 1px, transparent 1px)`,
        backgroundSize: "40px 40px"
      }} />
    </>
  ) : null;

  const footer = (
    <div className="slide-footer" style={{ color: theme.text }}>
      {index + 1} / {total}
    </div>
  );

  // Small colored icon badges for key points
  const iconColors = [theme.primary, theme.secondary, theme.accent, "#f59e0b"];

  switch (slide.layout) {
    case "title":
      return (
        <div className="slide-inner title-slide" style={{ ...bgStyle, color: theme.text, padding: style.padding }}>
          {decor}
          {/* Large subtle logo shape */}
          <div style={{
            position: "absolute", top: "50%", left: "50%", transform: "translate(-50%, -50%)",
            width: 280, height: 280, borderRadius: "50%",
            border: `1px solid ${theme.primary}15`, pointerEvents: "none"
          }} />
          <div style={{
            position: "absolute", top: "50%", left: "50%", transform: "translate(-50%, -50%)",
            width: 200, height: 200, borderRadius: "50%",
            border: `1px solid ${theme.primary}10`, pointerEvents: "none"
          }} />
          <div style={{ position: "relative", zIndex: 1, animation: "titleReveal 0.5s ease-out" }}>
            <div style={{ width: 50, height: 4, background: gradient, borderRadius: 2, margin: "0 auto 20px" }} />
            <h1 style={{
              fontSize: style.titleSize, fontWeight: 800, lineHeight: 1.15,
              background: gradient, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent",
              backgroundClip: "text", marginBottom: 20, letterSpacing: "-0.02em"
            }}>
              {slide.title}
            </h1>
            {slide.subtitle && (
              <p style={{ fontSize: 18, color: theme.textMuted, maxWidth: 500, margin: "0 auto", lineHeight: 1.6 }}>
                {slide.subtitle}
              </p>
            )}
          </div>
          <div className="accent-line" style={{ color: theme.primary }} />
          {footer}
        </div>
      );

    case "section":
      return (
        <div className="slide-inner" style={{ ...bgStyle, color: theme.text, padding: style.padding, justifyContent: "center" }}>
          {decor}
          <div style={{ position: "relative", zIndex: 1 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 24 }}>
              <div style={{ width: 48, height: 4, background: gradient, borderRadius: 2 }} />
              <div style={{ width: 8, height: 8, borderRadius: "50%", background: theme.primary, opacity: 0.5 }} />
            </div>
            <h1 style={{ fontSize: style.titleSize, fontWeight: 800, letterSpacing: "-0.03em" }}>{slide.title}</h1>
            {slide.subtitle && <p style={{ fontSize: 18, color: theme.textMuted, marginTop: 14, maxWidth: 500, lineHeight: 1.6 }}>{slide.subtitle}</p>}
          </div>
          <div className="accent-line" style={{ color: theme.secondary }} />
          {footer}
        </div>
      );

    case "bullets":
      return (
        <div className="slide-inner" style={{ ...bgStyle, color: theme.text, padding: style.padding }}>
          {decor}
          <div style={{ position: "relative", zIndex: 1 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 8 }}>
              <div style={{ width: 28, height: 3, background: gradient, borderRadius: 2 }} />
            </div>
            <h2 style={{ fontSize: style.headingSize, fontWeight: 700 }}>{slide.title}</h2>
          </div>
          <div className="slide-body" style={{ flex: 1, display: "flex", flexDirection: "column", justifyContent: "center", position: "relative", zIndex: 1 }}>
            <ul className="bullet-list">
              {(slide.bullets || []).map((b, i) => (
                <li key={i} style={{ color: theme.text, fontSize: style.bodySize }}>{b}</li>
              ))}
            </ul>
          </div>
          <div className="accent-line" style={{ color: theme.primary }} />
          {footer}
        </div>
      );

    case "two_column":
      return (
        <div className="slide-inner" style={{ ...bgStyle, color: theme.text, padding: style.padding }}>
          {decor}
          <div style={{ position: "relative", zIndex: 1 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 8 }}>
              <div style={{ width: 28, height: 3, background: gradient, borderRadius: 2 }} />
            </div>
            <h2 style={{ fontSize: style.headingSize, fontWeight: 700 }}>{slide.title}</h2>
          </div>
          <div className="two-column" style={{ position: "relative", zIndex: 1 }}>
            <ul className="bullet-list">
              {(slide.left?.bullets || []).map((b, i) => <li key={i} style={{ color: theme.text, fontSize: style.bodySize }}>{b}</li>)}
            </ul>
            <div className="visual-box" style={{ borderColor: theme.border }}>
              <span style={{ fontSize: 56, marginBottom: 12, filter: "drop-shadow(0 4px 8px rgba(0,0,0,0.3))" }}>
                {slide.right?.visual || "📊"}
              </span>
              {slide.right?.label && (
                <span style={{ fontSize: 14, color: theme.textMuted, textAlign: "center", lineHeight: 1.5 }}>
                  {slide.right.label}
                </span>
              )}
            </div>
          </div>
          <div className="accent-line" style={{ color: theme.primary }} />
          {footer}
        </div>
      );

    case "stats":
      return (
        <div className="slide-inner" style={{ ...bgStyle, color: theme.text, padding: style.padding }}>
          {decor}
          <div style={{ position: "relative", zIndex: 1 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 8 }}>
              <div style={{ width: 28, height: 3, background: gradient, borderRadius: 2 }} />
            </div>
            <h2 style={{ fontSize: style.headingSize, fontWeight: 700 }}>{slide.title}</h2>
          </div>
          <div className="stat-grid" style={{ position: "relative", zIndex: 1 }}>
            {(slide.stats || []).map((s, i) => (
              <div key={i} className="stat-card" style={{ borderColor: `${theme.primary}20` }}>
                <div style={{
                  fontSize: 40, fontWeight: 800,
                  background: gradient, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent",
                  backgroundClip: "text", marginBottom: 8, lineHeight: 1
                }}>
                  {s.number}
                </div>
                <div style={{ fontSize: 13, color: theme.textMuted, lineHeight: 1.4 }}>{s.label}</div>
                {/* Bottom accent bar */}
                <div style={{
                  position: "absolute", bottom: 0, left: "25%", right: "25%",
                  height: 3, background: gradient, borderRadius: "3px 3px 0 0", opacity: 0.5
                }} />
              </div>
            ))}
          </div>
          <div className="accent-line" style={{ color: theme.secondary }} />
          {footer}
        </div>
      );

    case "key_points":
      return (
        <div className="slide-inner" style={{ ...bgStyle, color: theme.text, padding: style.padding }}>
          {decor}
          <div style={{ position: "relative", zIndex: 1 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 8 }}>
              <div style={{ width: 28, height: 3, background: gradient, borderRadius: 2 }} />
            </div>
            <h2 style={{ fontSize: style.headingSize, fontWeight: 700 }}>{slide.title}</h2>
          </div>
          <div className="key-points" style={{ position: "relative", zIndex: 1 }}>
            {(slide.points || []).map((p, i) => (
              <div key={i} className="key-point-card" style={{ borderColor: `${iconColors[i % 4]}20`, position: "relative", overflow: "hidden" }}>
                {/* Colored left accent */}
                <div style={{ position: "absolute", left: 0, top: 0, bottom: 0, width: 3, background: iconColors[i % 4], borderRadius: "3px 0 0 3px" }} />
                <h4 style={{ fontSize: 15, fontWeight: 600, color: iconColors[i % 4], marginBottom: 8 }}>{p.title}</h4>
                <p style={{ fontSize: 13, color: theme.textMuted, lineHeight: 1.6 }}>{p.description}</p>
              </div>
            ))}
          </div>
          <div className="accent-line" style={{ color: theme.primary }} />
          {footer}
        </div>
      );

    case "flow":
      return (
        <div className="slide-inner" style={{ ...bgStyle, color: theme.text, padding: style.padding }}>
          {decor}
          <div style={{ position: "relative", zIndex: 1 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 8 }}>
              <div style={{ width: 28, height: 3, background: gradient, borderRadius: 2 }} />
            </div>
            <h2 style={{ fontSize: style.headingSize, fontWeight: 700 }}>{slide.title}</h2>
          </div>
          <div className="flow-row" style={{ position: "relative", zIndex: 1 }}>
            {(slide.steps || []).map((s, i) => (
              <div key={i} style={{ display: "flex", alignItems: "center" }}>
                <div className="diagram-box" style={{ borderColor: `${theme.primary}20`, color: theme.text, position: "relative", overflow: "hidden" }}>
                  {/* Step number badge */}
                  <div style={{
                    display: "inline-flex", alignItems: "center", justifyContent: "center",
                    width: 36, height: 36, borderRadius: "50%", background: gradient,
                    marginBottom: 10, fontSize: 16, fontWeight: 700, color: "#fff",
                    boxShadow: `0 4px 12px ${theme.primary}40`
                  }}>
                    {i + 1}
                  </div>
                  <div style={{ fontSize: 13, lineHeight: 1.4 }}>{s}</div>
                </div>
                {i < (slide.steps?.length || 0) - 1 && (
                  <span className="diagram-arrow" style={{ color: theme.primary, opacity: 0.4 }}>→</span>
                )}
              </div>
            ))}
          </div>
          <div className="accent-line" style={{ color: theme.secondary }} />
          {footer}
        </div>
      );

    case "quote":
      return (
        <div className="slide-inner" style={{ ...bgStyle, color: theme.text, padding: style.padding, justifyContent: "center", alignItems: "center", textAlign: "center" }}>
          {decor}
          {/* Large decorative quote mark */}
          <div className="quote-mark" style={{ color: theme.primary }}>&ldquo;</div>
          <div style={{ position: "relative", zIndex: 1, maxWidth: 620 }}>
            <div style={{
              width: 40, height: 3, background: gradient, borderRadius: 2, margin: "0 auto 28px"
            }} />
            <p style={{ fontSize: 22, fontStyle: "italic", fontWeight: 300, lineHeight: 1.7, letterSpacing: "0.01em" }}>
              {slide.quote}
            </p>
            {slide.attribution && (
              <div style={{ marginTop: 24, display: "flex", alignItems: "center", justifyContent: "center", gap: 10 }}>
                <div style={{ width: 24, height: 1, background: theme.textMuted, opacity: 0.3 }} />
                <p style={{ fontSize: 14, color: theme.textMuted }}>{slide.attribution}</p>
                <div style={{ width: 24, height: 1, background: theme.textMuted, opacity: 0.3 }} />
              </div>
            )}
          </div>
          <div className="accent-line" style={{ color: theme.primary }} />
          {footer}
        </div>
      );

    default:
      return (
        <div className="slide-inner" style={{ ...bgStyle, color: theme.text, padding: style.padding }}>
          {decor}
          <h2 style={{ fontSize: style.headingSize, fontWeight: 700, position: "relative", zIndex: 1 }}>{slide.title}</h2>
          <div style={{ flex: 1, display: "flex", flexDirection: "column", justifyContent: "center", position: "relative", zIndex: 1 }}>
            <ul className="bullet-list">
              {(slide.bullets || []).map((b, i) => <li key={i}>{b}</li>)}
            </ul>
          </div>
          {footer}
        </div>
      );
  }
}
